-- Car models:

INSERT INTO car_model(model_code, model, year, engine_power_kw, battery_kwh, range_mi, top_speed_mi, driveline, zero_sixty, towing_capacity, features, price, availability, motor, torque) 
VALUES("polestar2-dual-long-perfomance", "Polestar 2", "2024", 350, 82, 352, 127, "All-wheel drive", 4.0, 1500, "Electric power steering with three modes: light, standard and firm;Swedish gold Brembo four-piston fixed aluminium front calipers with drilled ventilated discs (with Performance pack;Ohlins Dual Flow Valve (DFV) Manually adjustable dampers (22 Settings) front and rear (with Performance pack);Turning circle 11,5 m", 57950, 45, "Dual Motor Perfomance", 740);
INSERT INTO car_model(model_code, model, year, engine_power_kw, battery_kwh, range_mi, top_speed_mi, driveline, zero_sixty, towing_capacity, features, price, availability, motor, torque) 
VALUES("polestar2-dual-long", "Polestar 2", "2024", 310, 82, 368, 127, "All-wheel drive", 4.3, 1500, "Electric power steering with three modes: light, standard and firm;Manually adjustable steering column;2-piston aluminium brakes, 345x30 mm (front) and 340x20 mm (rear) ventilated discs;Swedish gold Brembo four-piston fixed aluminium front calipers with drilled ventilated discs (with Performance pack;Twin tube, single-flow valve shock absorbers Suspension;Turning circle 11,5 m", 52950, 170, "Dual Motor", 740);
INSERT INTO car_model(model_code, model, year, engine_power_kw, battery_kwh, range_mi, top_speed_mi, driveline, zero_sixty, towing_capacity, features, price, availability, motor, torque) 
VALUES("polestar2-single-long", "Polestar 2", "2024", 220, 82, 406, 127, "Rear-wheel drive", 5.9, 1500, "Electric power steering with three modes: light, standard and firm;Manually adjustable steering column;2-piston aluminium brakes, 345x30 mm (front) and 340x20 mm (rear) ventilated discs;Swedish gold Brembo four-piston fixed aluminium front calipers with drilled ventilated discs (with Performance pack;Twin tube, single-flow valve shock absorbers Suspension;Turning circle 11,5 m", 48950, 154, "Single Motor", 490);
INSERT INTO car_model(model_code, model, year, engine_power_kw, battery_kwh, range_mi, top_speed_mi, driveline, zero_sixty, towing_capacity, features, price, availability, motor, torque) 
VALUES("polestar2-single-standard", "Polestar 2", "2024", 200, 69, 339, 127, "Rear-wheel drive", 6.2, 1500, "Electric power steering with three modes: light, standard and firm;Manually adjustable steering column;2-piston aluminium brakes, 345x30 mm (front) and 340x20 mm (rear) ventilated discs;Swedish gold Brembo four-piston fixed aluminium front calipers with drilled ventilated discs (with Performance pack;Dual Flow Valve (DFV) Manually adjustable dampers (22 Settings) front and rear (with Performance pack) Suspension;Turning circle 11,5 m", 44950, 179, "Single Motor", 490);

INSERT INTO car_model(model_code, model, year, engine_power_kw, battery_kwh, range_mi, top_speed_mi, driveline, zero_sixty, towing_capacity, features, price, availability, motor, torque) 
VALUES("polestar3-single-long", "Polestar 3", "2024", 220, 111, 403, 112, "Rear-wheel drive", 7.5, 1500, "Power-operated steering column;Rear-wheel drive with all single motor variants;Standard anodised brake callipers, with ventilated 390-mm discs (Swedish gold callipers with Performance pack);Passive chassis for Long range Single motor variant;Double wishbone front suspension;Integral link rear suspension;Turning circle 11.8 m (kerb to kerb)", 69900, 23, "Single Motor", 490);
INSERT INTO car_model(model_code, model, year, engine_power_kw, battery_kwh, range_mi, top_speed_mi, driveline, zero_sixty, towing_capacity, features, price, availability, motor, torque) 
VALUES("polestar3-dual-long", "Polestar 3", "2024", 360, 111, 392, 130, "All-wheel drive", 4.8, 2200, "Electric power steering with three modes: standard, firm and light;All-wheel drive with all single motor variants;Aluminium 4-piston anodised brake callipers, with ventilated 400-mm discs (Swedish gold callipers with Performance pack);Dynamic chassis for Long range Dual motor variants;Double wishbone front suspension;Integral link rear suspension;Dual chamber active air suspension with standard, nimble, and firm settings, loading mode, and automatic ride height adjustment to optimise aerodynamics (Long range Dual motor);Turning circle 11.8 m (kerb to kerb)", 75900, 40, "Dual Motor", 840);
INSERT INTO car_model(model_code, model, year, engine_power_kw, battery_kwh, range_mi, top_speed_mi, driveline, zero_sixty, towing_capacity, features, price, availability, motor, torque) 
VALUES("polestar3-dual-long-perfomance", "Polestar 3", "2024", 380, 111, 348, 130, "All-wheel drive", 4.5, 2200, "Electric power steering with three modes: standard, firm and light;All-wheel drive with all single motor variants;Brake-by-wire system with Brembo performance brakes;Polestar Engineered chassis tuning (with Performance pack);Double wishbone front suspension;Integral link rear suspension;Dual chamber active air suspension with standard, nimble, and firm settings, loading mode, and automatic ride height adjustment to optimise aerodynamics (Long range Dual motor);Turning circle 11.8 m (kerb to kerb)", 81500, 11, "Dual Motor Perfomance", 910);

INSERT INTO car_model(model_code, model, year, engine_power_kw, battery_kwh, range_mi, top_speed_mi, driveline, zero_sixty, towing_capacity, features, price, availability, motor, torque) 
VALUES("polestar4-single-long", "Polestar 4", "2024", 200, 100, 385, 124, "Rear-wheel drive", 6.9, 1500, "Manually adjustable steering column;Brakes: 364 x 30 mm (front) and 350 x 26 mm (rear) ventilated discs with 2 x 43 mm-piston aluminium callipers;Standard dynamic chassis;Suspension: High-capacity passive dampers with internal rebound coil springs, combined with external coil springs;Turning circle (kerb to kerb) 11.64 m", 59990, 34, "Single Motor", 253);
INSERT INTO car_model(model_code, model, year, engine_power_kw, battery_kwh, range_mi, top_speed_mi, driveline, zero_sixty, towing_capacity, features, price, availability, motor, torque) 
VALUES("polestar4-dual-long", "Polestar 4", "2024", 200, 100, 367, 124, "All-wheel drive", 3.7, 2000, "Electric power steering with three modes: light, standard, and firm;Brakes: 364 x 30 mm (front) and 350 x 26 mm (rear) ventilated discs with 2 x 45 mm-piston aluminium callipers;Polestar Engineered chassis tuning;Suspension: Continuously controlled active ZF dampers with coil spring suspension (CCD) equipped with internal valve and rebound coil springs and external coil springs;Turning circle (kerb to kerb) 11.64 m", 66990, 10, "Dual Motor", 506);