/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TestDriveImport } from './routes/test-drive'
import { Route as ServicingImport } from './routes/servicing'
import { Route as RegisterImport } from './routes/register'
import { Route as NewVehiclesImport } from './routes/new-vehicles_'
import { Route as CustomVehicleImport } from './routes/custom-vehicle_'
import { Route as ChargingImport } from './routes/charging'
import { Route as AuthImport } from './routes/auth'
import { Route as AdminImport } from './routes/admin_'
import { Route as AdminAuthImport } from './routes/admin-auth'
import { Route as IndexImport } from './routes/index'
import { Route as NewVehiclesCarPropsImport } from './routes/new-vehicles.$carProps'
import { Route as CustomVehicleModelCodeImport } from './routes/custom-vehicle.$modelCode'
import { Route as AdminTestDrivesImport } from './routes/admin/test-drives'
import { Route as AdminServiceRequestsImport } from './routes/admin/service-requests'
import { Route as AdminNewVehiclesImport } from './routes/admin/new-vehicles'
import { Route as AdminCustomVehiclesImport } from './routes/admin/custom-vehicles'
import { Route as AdminChargersImport } from './routes/admin/chargers'
import { Route as AdminChargerOrdersImport } from './routes/admin/charger-orders'
import { Route as AdminCarOrdersImport } from './routes/admin/car-orders'
import { Route as AdminBackupRestoreImport } from './routes/admin/backup-restore'
import { Route as AdminServiceRequestsIdImport } from './routes/admin/service-requests.$id'

// Create/Update Routes

const TestDriveRoute = TestDriveImport.update({
  path: '/test-drive',
  getParentRoute: () => rootRoute,
} as any)

const ServicingRoute = ServicingImport.update({
  path: '/servicing',
  getParentRoute: () => rootRoute,
} as any)

const RegisterRoute = RegisterImport.update({
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const NewVehiclesRoute = NewVehiclesImport.update({
  path: '/new-vehicles',
  getParentRoute: () => rootRoute,
} as any)

const CustomVehicleRoute = CustomVehicleImport.update({
  path: '/custom-vehicle',
  getParentRoute: () => rootRoute,
} as any)

const ChargingRoute = ChargingImport.update({
  path: '/charging',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const AdminRoute = AdminImport.update({
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const AdminAuthRoute = AdminAuthImport.update({
  path: '/admin-auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const NewVehiclesCarPropsRoute = NewVehiclesCarPropsImport.update({
  path: '/new-vehicles/$carProps',
  getParentRoute: () => rootRoute,
} as any)

const CustomVehicleModelCodeRoute = CustomVehicleModelCodeImport.update({
  path: '/custom-vehicle/$modelCode',
  getParentRoute: () => rootRoute,
} as any)

const AdminTestDrivesRoute = AdminTestDrivesImport.update({
  path: '/admin/test-drives',
  getParentRoute: () => rootRoute,
} as any)

const AdminServiceRequestsRoute = AdminServiceRequestsImport.update({
  path: '/admin/service-requests',
  getParentRoute: () => rootRoute,
} as any)

const AdminNewVehiclesRoute = AdminNewVehiclesImport.update({
  path: '/admin/new-vehicles',
  getParentRoute: () => rootRoute,
} as any)

const AdminCustomVehiclesRoute = AdminCustomVehiclesImport.update({
  path: '/admin/custom-vehicles',
  getParentRoute: () => rootRoute,
} as any)

const AdminChargersRoute = AdminChargersImport.update({
  path: '/admin/chargers',
  getParentRoute: () => rootRoute,
} as any)

const AdminChargerOrdersRoute = AdminChargerOrdersImport.update({
  path: '/admin/charger-orders',
  getParentRoute: () => rootRoute,
} as any)

const AdminCarOrdersRoute = AdminCarOrdersImport.update({
  path: '/admin/car-orders',
  getParentRoute: () => rootRoute,
} as any)

const AdminBackupRestoreRoute = AdminBackupRestoreImport.update({
  path: '/admin/backup-restore',
  getParentRoute: () => rootRoute,
} as any)

const AdminServiceRequestsIdRoute = AdminServiceRequestsIdImport.update({
  path: '/$id',
  getParentRoute: () => AdminServiceRequestsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin-auth': {
      id: '/admin-auth'
      path: '/admin-auth'
      fullPath: '/admin-auth'
      preLoaderRoute: typeof AdminAuthImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/charging': {
      id: '/charging'
      path: '/charging'
      fullPath: '/charging'
      preLoaderRoute: typeof ChargingImport
      parentRoute: typeof rootRoute
    }
    '/custom-vehicle': {
      id: '/custom-vehicle'
      path: '/custom-vehicle'
      fullPath: '/custom-vehicle'
      preLoaderRoute: typeof CustomVehicleImport
      parentRoute: typeof rootRoute
    }
    '/new-vehicles': {
      id: '/new-vehicles'
      path: '/new-vehicles'
      fullPath: '/new-vehicles'
      preLoaderRoute: typeof NewVehiclesImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/servicing': {
      id: '/servicing'
      path: '/servicing'
      fullPath: '/servicing'
      preLoaderRoute: typeof ServicingImport
      parentRoute: typeof rootRoute
    }
    '/test-drive': {
      id: '/test-drive'
      path: '/test-drive'
      fullPath: '/test-drive'
      preLoaderRoute: typeof TestDriveImport
      parentRoute: typeof rootRoute
    }
    '/admin/backup-restore': {
      id: '/admin/backup-restore'
      path: '/admin/backup-restore'
      fullPath: '/admin/backup-restore'
      preLoaderRoute: typeof AdminBackupRestoreImport
      parentRoute: typeof rootRoute
    }
    '/admin/car-orders': {
      id: '/admin/car-orders'
      path: '/admin/car-orders'
      fullPath: '/admin/car-orders'
      preLoaderRoute: typeof AdminCarOrdersImport
      parentRoute: typeof rootRoute
    }
    '/admin/charger-orders': {
      id: '/admin/charger-orders'
      path: '/admin/charger-orders'
      fullPath: '/admin/charger-orders'
      preLoaderRoute: typeof AdminChargerOrdersImport
      parentRoute: typeof rootRoute
    }
    '/admin/chargers': {
      id: '/admin/chargers'
      path: '/admin/chargers'
      fullPath: '/admin/chargers'
      preLoaderRoute: typeof AdminChargersImport
      parentRoute: typeof rootRoute
    }
    '/admin/custom-vehicles': {
      id: '/admin/custom-vehicles'
      path: '/admin/custom-vehicles'
      fullPath: '/admin/custom-vehicles'
      preLoaderRoute: typeof AdminCustomVehiclesImport
      parentRoute: typeof rootRoute
    }
    '/admin/new-vehicles': {
      id: '/admin/new-vehicles'
      path: '/admin/new-vehicles'
      fullPath: '/admin/new-vehicles'
      preLoaderRoute: typeof AdminNewVehiclesImport
      parentRoute: typeof rootRoute
    }
    '/admin/service-requests': {
      id: '/admin/service-requests'
      path: '/admin/service-requests'
      fullPath: '/admin/service-requests'
      preLoaderRoute: typeof AdminServiceRequestsImport
      parentRoute: typeof rootRoute
    }
    '/admin/test-drives': {
      id: '/admin/test-drives'
      path: '/admin/test-drives'
      fullPath: '/admin/test-drives'
      preLoaderRoute: typeof AdminTestDrivesImport
      parentRoute: typeof rootRoute
    }
    '/custom-vehicle/$modelCode': {
      id: '/custom-vehicle/$modelCode'
      path: '/custom-vehicle/$modelCode'
      fullPath: '/custom-vehicle/$modelCode'
      preLoaderRoute: typeof CustomVehicleModelCodeImport
      parentRoute: typeof rootRoute
    }
    '/new-vehicles/$carProps': {
      id: '/new-vehicles/$carProps'
      path: '/new-vehicles/$carProps'
      fullPath: '/new-vehicles/$carProps'
      preLoaderRoute: typeof NewVehiclesCarPropsImport
      parentRoute: typeof rootRoute
    }
    '/admin/service-requests/$id': {
      id: '/admin/service-requests/$id'
      path: '/$id'
      fullPath: '/admin/service-requests/$id'
      preLoaderRoute: typeof AdminServiceRequestsIdImport
      parentRoute: typeof AdminServiceRequestsImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AdminAuthRoute,
  AdminRoute,
  AuthRoute,
  ChargingRoute,
  CustomVehicleRoute,
  NewVehiclesRoute,
  RegisterRoute,
  ServicingRoute,
  TestDriveRoute,
  AdminBackupRestoreRoute,
  AdminCarOrdersRoute,
  AdminChargerOrdersRoute,
  AdminChargersRoute,
  AdminCustomVehiclesRoute,
  AdminNewVehiclesRoute,
  AdminServiceRequestsRoute: AdminServiceRequestsRoute.addChildren({
    AdminServiceRequestsIdRoute,
  }),
  AdminTestDrivesRoute,
  CustomVehicleModelCodeRoute,
  NewVehiclesCarPropsRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin-auth",
        "/admin",
        "/auth",
        "/charging",
        "/custom-vehicle",
        "/new-vehicles",
        "/register",
        "/servicing",
        "/test-drive",
        "/admin/backup-restore",
        "/admin/car-orders",
        "/admin/charger-orders",
        "/admin/chargers",
        "/admin/custom-vehicles",
        "/admin/new-vehicles",
        "/admin/service-requests",
        "/admin/test-drives",
        "/custom-vehicle/$modelCode",
        "/new-vehicles/$carProps"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admin-auth": {
      "filePath": "admin-auth.tsx"
    },
    "/admin": {
      "filePath": "admin_.tsx"
    },
    "/auth": {
      "filePath": "auth.tsx"
    },
    "/charging": {
      "filePath": "charging.tsx"
    },
    "/custom-vehicle": {
      "filePath": "custom-vehicle_.tsx"
    },
    "/new-vehicles": {
      "filePath": "new-vehicles_.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/servicing": {
      "filePath": "servicing.tsx"
    },
    "/test-drive": {
      "filePath": "test-drive.tsx"
    },
    "/admin/backup-restore": {
      "filePath": "admin/backup-restore.tsx"
    },
    "/admin/car-orders": {
      "filePath": "admin/car-orders.tsx"
    },
    "/admin/charger-orders": {
      "filePath": "admin/charger-orders.tsx"
    },
    "/admin/chargers": {
      "filePath": "admin/chargers.tsx"
    },
    "/admin/custom-vehicles": {
      "filePath": "admin/custom-vehicles.tsx"
    },
    "/admin/new-vehicles": {
      "filePath": "admin/new-vehicles.tsx"
    },
    "/admin/service-requests": {
      "filePath": "admin/service-requests.tsx",
      "children": [
        "/admin/service-requests/$id"
      ]
    },
    "/admin/test-drives": {
      "filePath": "admin/test-drives.tsx"
    },
    "/custom-vehicle/$modelCode": {
      "filePath": "custom-vehicle.$modelCode.tsx"
    },
    "/new-vehicles/$carProps": {
      "filePath": "new-vehicles.$carProps.tsx"
    },
    "/admin/service-requests/$id": {
      "filePath": "admin/service-requests.$id.tsx",
      "parent": "/admin/service-requests"
    }
  }
}
ROUTE_MANIFEST_END */
